const skills = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Ruby",
  "Java",
  "C#",
  "C Language",
  "C++",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "PHP",
  "Perl",
  "HTML",
  "CSS",
  "SASS",
  "SCSS",
  "SQL",
  "NoSQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "GraphQL",
  "RESTful APIs",
  "Node.js",
  "Express.js",
  "React",
  "Vue.js",
  "Angular",
  "Svelte",
  "Redux",
  "React Native",
  "Flutter",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Electron",
  "Next.js",
  "Gatsby",
  "Laravel",
  "Ruby on Rails",
  "Spring Boot",
  "Django",
  "Flask",
  "ASP.NET",
  "Firebase",
  "WordPress",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Jenkins",
  "Terraform",
  "AWS",
  "Google Cloud",
  "Azure",
  "Firebase",
  "Heroku",
  "Netlify",
  "Vercel",
  "Nginx",
  "Apache",
  "Linux",
  "Unix",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "SVN",
  "Agile",
  "Scrum",
  "JIRA",
  "Trello",
  "VS Code",
  "IntelliJ IDEA",
  "Sublime Text",
  "Eclipse",
  "Android Development",
  "iOS Development",
  "Xcode",
  "Android Studio",
  "Unit Testing",
  "TDD",
  "Jest",
  "Mocha",
  "Chai",
  "Cypress",
  "Karma",
  "Jasmine",
  "Puppeteer",
  "Selenium",
  "Postman",
  "Figma",
  "Adobe XD",
  "Sketch",
  "WebAssembly",
  "Socket.io",
  "WebSockets",
  "GraphQL",
  "ElasticSearch",
  "Redis",
  "RabbitMQ",
  "Celery",
  "WebRTC",
  "OAuth",
  "JWT",
  "Single Sign-On",
  "Social Login",

  "Communication",
  "Teamwork",
  "Leadership",
  "Problem Solving",
  "Adaptability",
  "Critical Thinking",
  "Time Management",
  "Creativity",
  "Conflict Resolution",
  "Negotiation",
  "Empathy",
  "Collaboration",
  "Emotional Intelligence",
  "Mentorship",
  "Public Speaking",
  "Networking",
  "Active Listening",
  "Decision Making",
  "Presentation Skills",
  "Customer Service",
  "Decision Making",
  "Project Management",
  "Stress Management",
  "Self-Motivation",
  "Delegation",
  "Conflict Mediation",
  "Conflict Management",
  "Attention to Detail",
  "Focus",
  "Organization",
  "Multitasking",
  "Work-Life Balance",
  "Mindfulness",
  "Patience",
  "Initiative",

  "Business Strategy",
  "Entrepreneurship",
  "Product Management",
  "Market Research",
  "Business Development",
  "Sales",
  "Marketing",
  "Branding",
  "Digital Marketing",
  "Customer Success",
  "Financial Modeling",
  "Venture Capital",
  "Project Management",
  "Operations Management",
  "Risk Management",
  "Supply Chain Management",
  "Lean Methodology",
  "Scrum",
  "Agile",
  "Stakeholder Management",
  "Negotiation",
  "Budgeting",
  "Revenue Growth",
  "Data Analysis",
  "Excel",
  "PowerPoint",
  "Excel VBA",
  "Financial Planning",
  "Business Analytics",
  "Cost Optimization",

  "UX/UI Design",
  "Wireframing",
  "Prototyping",
  "User Research",
  "Visual Design",
  "Interaction Design",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Sketch",
  "Figma",
  "InVision",
  "Canva",
  "Design Thinking",
  "Typography",
  "Color Theory",
  "Branding",
  "Illustration",
  "Motion Graphics",
  "Logo Design",
  "Marketing Design",
  "3D Modeling",
  "Animation",
  "Web Design",
  "Responsive Design",
  "HTML/CSS",
  "CSS Animations",
  "Wireframing",
  "Adobe After Effects",
  "InDesign",
  "User Flows",
  "Figma Design Systems",
  "User Interface",
  "Art Direction",
  "Photography",
  "Video Editing",
  "Storyboard",
  "Editing",
  "Film Production",
  "Photo Manipulation",
  "Creative Writing",
  "Copywriting",
  "Storytelling",
  "Copy Editing",
  "Content Strategy",

  "English",
  "Spanish",
  "French",
  "German",
  "Chinese",
  "Japanese",
  "Russian",
  "Arabic",
  "Portuguese",
  "Italian",
  "Hindi",
  "Mandarin",
  "Bengali",
  "Korean",
  "Dutch",
  "Swedish",
  "Turkish",
  "Polish",
  "Ukrainian",
  "Hebrew",
  "Czech",
  "Finnish",
  "Greek",
  "Norwegian",
  "Hungarian",
  "Indonesian",
  "Thai",
  "Vietnamese",

  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Data Analysis",
  "Data Visualization",
  "Big Data",
  "Python",
  "R",
  "MATLAB",
  "Pandas",
  "NumPy",
  "TensorFlow",
  "PyTorch",
  "OpenCV",
  "Keras",
  "SQL",
  "Hadoop",
  "Spark",
  "Data Mining",
  "Algorithm Development",
  "Data Modeling",
  "Time Series Analysis",
  "Predictive Modeling",
  "Data Cleansing",
  "Feature Engineering",
  "Model Evaluation",
  "Reinforcement Learning",
  "Computer Vision",
  "AI Ethics",
  "Artificial Intelligence",
  "Statistics",
  "R Programming",
  "SQL Queries",
  "Tableau",
  "Power BI",

  "Ethical Hacking",
  "Network Security",
  "Cryptography",
  "Firewalls",
  "SIEM",
  "Risk Assessment",
  "Vulnerability Management",
  "Incident Response",
  "Malware Analysis",
  "Data Encryption",
  "Threat Hunting",
  "Intrusion Detection",
  "SOC",
  "Zero Trust Security",
  "Security Auditing",
  "GDPR Compliance",
  "HIPAA Compliance",
  "Access Control",
  "Encryption Algorithms",
  "Cyber Threat Intelligence",
  "Security Architecture",
  "Wireshark",
  "Security Operations",

  "AWS",
  "Azure",
  "Google Cloud",
  "Heroku",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "CI/CD",
  "DevOps",
  "AWS Lambda",
  "Google Cloud Functions",
  "Jenkins",
  "Travis CI",
  "CircleCI",
  "Bitbucket",
  "GitLab",
  "Vagrant",
  "Nginx",
  "Apache",
  "CloudFormation",
  "Elastic Beanstalk",
  "Cloud Security",
  "Infrastructure as Code",
  "GitOps",
  "Monitoring",
  "Logging",
  "Data Center Management",

  "Search Engine Optimization (SEO)",
  "Content Marketing",
  "Social Media Marketing",
  "Google Analytics",
  "Google Ads",
  "Facebook Ads",
  "PPC",
  "Email Marketing",
  "Affiliate Marketing",
  "Influencer Marketing",
  "SEO Copywriting",
  "Lead Generation",
  "SEO Tools",
  "Keyword Research",
  "Link Building",
  "Marketing Strategy",
  "Conversion Rate Optimization",
  "Marketing Automation",
  "Brand Strategy",
  "Content Strategy",
  "Marketing Research",
  "Video Marketing",

  "Photography",
  "Video Production",
  "Event Planning",
  "Public Speaking",
  "Fundraising",
  "Life Coaching",
  "Yoga",
  "Meditation",
  "Fitness",
  "Travel",
  "Public Relations",
  "Entrepreneurship",
  "Design Thinking",
  "Social Media Management",
  "Community Management",
  "Podcasting",
  "Public Relations",
  "Speech Writing",
  "Team Building",
];

module.exports = { skills };
